In [34]:
import pandas as pd
import numpy as np

from catboost import CatBoostRegressor

import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import trange
from tqdm.cli import tqdm

## prepocessing

In [35]:
df_belchonok = pd.read_csv('./preprocessed_data/belchonok.csv')
df_future = pd.read_csv('./preprocessed_data/future.csv')
df_granit = pd.read_csv('./preprocessed_data/granit_nauki.csv')
df_innopolis = pd.read_csv('./preprocessed_data/innopolis.csv')
df_itmo = pd.read_csv('./preprocessed_data/itmo.csv')
df_mosh = pd.read_csv('./preprocessed_data/mosh.csv')
df_open = pd.read_csv('./preprocessed_data/open.csv')
df_vuz = pd.read_csv('./preprocessed_data/vuz_akadem.csv')
df_mow_sch = pd.read_csv('./preprocessed_data/MOW_SCH.csv')
df_mow_mun = pd.read_csv('./preprocessed_data/MOW_MUN.csv')
df_reg = pd.read_csv('./preprocessed_data/reg.csv')
df_arso_fin = pd.read_csv('./preprocessed_data/fin.csv')

### Фильтрация по участникам

In [36]:
df_arso_fin = df_arso_fin.sort_values(by=['year', 'score'], ascending=[True, False])
df_arso_fin.head()

,place,name,region,class_study,p1,p2,p3,p4,p5,p6,p7,p8,score,title,year
0,1,Грекова Д.,Москва,11,100,100,100,70,100,88,86,80,724,1,24-25
1,2,Абдуллин Г.,Республика Татарстан,11,100,100,100,70,100,100,70,80,720,1,24-25
2,3,Жиганов В.,Москва,10,100,100,88,60,100,100,66,68,682,1,24-25
3,4,Звездин В.,Санкт-Петербург,10,100,100,100,70,100,76,66,64,676,1,24-25
4,5,Иванов Н.,Москва,11,100,100,88,65,100,100,65,50,668,1,24-25

#### Проблема с совпадением фамилия + первая буква имени

In [37]:
names = df_arso_fin['name'].value_counts().keys().to_numpy()

In [38]:
names[df_arso_fin['name'].value_counts() > 2]

array(['Макаров М.', 'Закиров А.', 'Торба А.', 'Андреев А.', 'Осипов Д.',
       'Зайцев А.', 'Соколов М.'], dtype=object)

In [39]:
df_arso_fin['name'].value_counts()

name
Макаров М.       4
Закиров А.       4
Торба А.         3
Андреев А.       3
Осипов Д.        3
                ..
Виноградов П.    1
Зуева А.         1
Кочуров Е.       1
Курзин И.        1
Яковлева П.      1
Name: count, Length: 719, dtype: int64

In [40]:
df_arso_fin[df_arso_fin['name'].isin(names[df_arso_fin['name'].value_counts() > 2])].sort_values(by=['place'], ascending=[True])

,place,name,region,class_study,p1,p2,p3,p4,p5,p6,p7,p8,score,title,year
505,13,Макаров М.,Москва,11,100,100,26,40,100,100,89,34,589,1.0,25-26
508,16,Макаров М.,Москва,11,100,100,20,31,100,95,100,25,571,1.0,25-26
28,29,Макаров М.,Москва,10,100,100,63,0,100,100,65,60,588,1,24-25
528,35,Закиров А.,Республика Татарстан,10,100,100,26,35,100,85,59,32,537,1.0,25-26
41,41,Закиров А.,Республика Татарстан,9,100,100,63,44,100,71,55,33,566,2,24-25
534,42,Закиров А.,Республика Татарстан,11,100,100,20,32,100,85,59,34,530,2.0,25-26
98,99,Торба А.,Москва,10,100,86,49,30,100,66,40,46,517,2,24-25
107,108,Закиров А.,Республика Татарстан,10,100,100,51,16,100,76,50,17,510,2,24-25
604,111,Торба А.,Москва,11,100,46,26,41,100,85,59,25,482,2.0,25-26
606,113,Андреев А.,Ростовская область,11,100,51,26,35,100,85,59,25,481,2.0,25-26
148,148,Макаров М.,Москва,10,100,100,0,37,100,100,0,46,483,2,24-25
702,209,Зайцев А.,Липецкая область,10,100,55,0,21,100,85,59,16,436,2.0,25-26
704,209,Осипов Д.,Республика Татарстан,11,100,100,20,0,100,85,23,8,436,2.0,25-26
212,213,Андреев А.,Липецкая область,9,100,64,9,24,100,83,46,21,447,2,24-25
718,226,Андреев А.,Липецкая область,10,100,24,20,18,100,85,59,25,431,2.0,25-26
738,245,Соколов М.,Санкт-Петербург,10,100,9,20,23,100,85,59,27,423,NaN,25-26
253,254,Осипов Д.,Москва,11,100,0,65,16,100,71,50,13,415,\n,24-25
801,308,Зайцев А.,Республика Татарстан,10,100,14,20,13,100,85,48,6,386,NaN,25-26
307,308,Зайцев А.,Липецкая область,9,100,5,9,30,100,74,22,36,376,\n,24-25
326,326,Соколов М.,Санкт-Петербург,9,100,11,16,0,100,88,43,0,358,\n,24-25
341,342,Осипов Д.,Республика Татарстан,10,100,0,0,16,100,100,33,0,349,\n,24-25
946,454,Соколов М.,Москва,9,100,35,20,21,25,15,35,6,257,NaN,25-26
953,460,Торба А.,Москва,8,100,20,13,17,25,40,10,6,231,NaN,25-26

**РЕШЕНИЕ**:
ликвидация

In [41]:
names2drop = names[df_arso_fin['name'].value_counts() > 2]

df_arso_fin = df_arso_fin[~df_arso_fin['name'].isin(names2drop)]
df_arso_fin.head()

TypeError: dtype 'str' does not support operation 'mean'